# Generated by Django 2.0.13 on 2020-01-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('favorite_color', models.CharField(max_length=20)),
                ('cats_or_dogs', models.CharField(max_length=20)),
            ],
        ),
    ]
